CREATE DATABASE IF NOT EXISTS test_ensolvers DEFAULT CHARACTER SET utf8;

USE test_ensolvers;

CREATE TABLE IF NOT EXISTS users(
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	name VARCHAR(70) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS folders(
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	name VARCHAR(30) NOT NULL,
	created_at DATETIME NOT NULL,
    user_id INT NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items(
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
    done BOOL NOT NULL DEFAULT false,
    folder_id INT NOT NULL,
    FOREIGN KEY(folder_id) REFERENCES folders(id) ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY(id)
);